catalogo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from dashboard.views import index_dashboard, crear_producto_dashboard, borrar_producto_dashboard, \
    editar_producto_dashboard

app_name = 'dashboard'

urlpatterns = [
    path('', index_dashboard, name='index'),
    path('crear-producto/', crear_producto_dashboard, name='crear_producto'),
    path('borar-producto/<int:pk>/', borrar_producto_dashboard, name='borrar_producto'),
    path('editar-producto/<int:pk>/', editar_producto_dashboard, name='editar_producto'),

]

website/urls.py
from django.urls import path

from .views import index_website, detalle_producto

app_name = 'website'

urlpatterns = [
    path('', index_website, name='index_website'),
    path('detalle-producto/<int:pk>/', detalle_producto, name='detalle_producto'),

]

dashboard/models.py
from django.db import models

# Create your models here.

productos/models.py
from django.db import models


class ImagenesProducto(models.Model):
    nombre = models.CharField(max_length=250, blank=True)
    imagen = models.ImageField(blank=True, null=True)


class Producto(models.Model):
    nombre = models.CharField(max_length=250)
    imagen = models.ImageField()
    descripcion = models.CharField(max_length=250, blank=True)
    precio = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    activo = models.BooleanField(default=False)
    galeria = models.ManyToManyField(ImagenesProducto)

    def __str__(self):
        return self.nombre

website/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from productos.models import Producto


class CrearProductoForm(forms.Form):
    nombre = forms.CharField()
    imagen = forms.ImageField()


class CrearProductoModelForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields='__all__'
        #fields = ['nombre', 'imagen']

dashboard/views.py
from django.shortcuts import render, redirect

from productos.models import Producto
from .forms import CrearProductoModelForm


# Create your views here.

def index_dashboard(request):
    objects_list = Producto.objects.all()
    context = {
        'objects_list': objects_list
    }
    return render(request, 'dashboard/index.html', context)


def crear_producto_dashboard(request):
    form = CrearProductoModelForm
    if request.method == 'POST':
        form = CrearProductoModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('dashboard:index')
    return render(request, 'dashboard/crear_producto.html', {'form': form, 'titulo': 'Nuevo Producto'})


def borrar_producto_dashboard(request, pk):
    Producto.objects.get(pk=pk).delete()
    return redirect('dashboard:index')


def editar_producto_dashboard(request, pk):
    producto = Producto.objects.get(pk=pk)
    form = CrearProductoModelForm(instance=producto)
    if request.method == 'POST':
        form = CrearProductoModelForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
        return redirect('dashboard:index')
    return render(request, 'dashboard/crear_producto.html', {'form': form, 'titulo': 'Actuliazar Producto'})

productos/views.py
from django.shortcuts import render

# Create your views here.

website/views.py
from django.shortcuts import render

from productos.models import Producto


def index_website(request):
    objects_list = Producto.objects.all()
    context = {
        'objects_list': objects_list
    }

    return render(request, 'website/index.html', context)


def detalle_producto(request, pk):
    producto = Producto.objects.get(pk=pk)
    return render(request, 'website/detalle_producto.html', {'producto': producto})

dashboard/templates/dashboard/crear_producto.html
{% extends 'basebs5.html' %}

{% block titulo_tab %}
{{ titulo}} - Dashboard
{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Dashboard Administrativo</h1>
                <h2>{{ titulo}}</h2>
                <a href="{% url 'dashboard:index' %}" class="btn btn-warning"> <- Inicio</a>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table table-bordered table-hover mt-4">
                        {{ form.as_table }}
                        <tr>
                            <td colspan="2" class="text-end">
                                <input type="submit" class="btn btn-dark" value="Guardar">

                            </td>
                        </tr>

                    </table>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'basebs5.html' %}

{% block titulo_tab %}
    Dashboard - Administrativo
{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Dashboard Administrativo</h1>
                <a href="{% url 'dashboard:crear_producto' %}" class="btn btn-warning">+ Producto</a>
                <table class="table table-bordered table-hover mt-4">
                    <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Imagen</th>
                        <th>Opciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for objects in objects_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ objects.nombre }}</td>
                            <td class="text-center">
                                <img src="{{ objects.imagen.url }}" class="img-thumbnail" style="width: 100px">
                            </td>
                            <td>
                                <a href="{% url 'dashboard:borrar_producto' objects.pk %}"
                                   class="btn btn-sm btn-dark">Borrar</a>
                                <a href="{% url 'dashboard:editar_producto' objects.pk %}" class="btn btn-sm btn-warning">Editar</a>
                            </td>
                        </tr>
                    {% endfor %}


                    </tbody>

                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/basebs5.html
{% load static %}
{% comment %}
Template basado en Boostrab 5.2.2
Autor: Francisco Javier
Fecha: 31/10/2022
{% endcomment %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block titulo_tab %}
            Titulo
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'bs522/css/bootstrap.min.css' %}">
</head>
<body>

{% block contenido %}

{% endblock %}

<script src="{% static 'bs522/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

website/templates/website/base.html
{% load static %}

<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block titulo_tab %}
            Catalogo
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'bs522/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fa_all.min.css' %}">
</head>
<body>

{% block contenido %}
    <h1>Mi Catalogo</h1>
{% endblock %}

<script src="{% static 'bs522/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/fa_all.min.js' %}"></script>
</body>
</html>

website/templates/website/detalle_producto.html
{% extends 'website/base.html' %}
{% block titulo_tab %}
    {{ producto.nombre }} - Detalle
{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 style="color: mediumblue">
                    <a href="{% url 'website:index_website' %}"><i class="fa-solid fa-arrow-left"></i></a>
                    {{ producto.nombre }}
                </h1>
                <img src="{{ producto.imagen.url }}" alt="Foto Producto">
                <div>
                    {% for obj in producto.galeria.all %}
                        <p>{{ obj.nombre }}</p>
                        <img src="{{ obj.imagen.url }}" alt="" class="img-thumbnail w-25">

                    {% endfor %}
                </div>

                <h3 style="color: #bb2d3b">{{ producto.descripcion }}</h3>
                <br>
                <a href="#" class="btn btn-primary">${{ producto.precio }}</a>
                <br>
                <br>
                <h2>
                    <a href="https://api.whatsapp.com/send?phone=529933070285&text=Quiero comprar estes producto {{ producto.nombre }} https://127.0.0.1:8000 {{ request.path }}"
                       class="text-success" target="_blank">
                        <i class="fa-brands fa-whatsapp"></i>
                        Ordenar
                    </a>
                </h2>

            </div>

        </div>
    </div>

{% endblock %}

website/templates/website/index.html
{% extends 'website/base.html' %}
{% block titulo_tab %}
    Inicio - Catalogo
{% endblock %}

{% block contenido %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Fondita "lo mas Barato"</h1>
                {% for objects in objects_list %}
                    {% if objects.activo %}
                        <div class="card" style="width: 18rem;">
                            <img src="{{ objects.imagen.url }}" class="card-img-top" alt="Foto Comida">
                            <div class="card-body">
                                <h5 class="card-title">{{ objects.nombre }}</h5>
                                {#                            <p class="card-text">Some quick example text to build on the card title and make up the bulk#}
                                {#                                of the card's content.</p>#}
                                <a href="{% url 'website:detalle_producto' objects.pk %}"
                                   class="btn btn-primary">${{ objects.precio }}</a>
                            </div>
                        </div>

                    {% endif %}

                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}